server:
  port: 8099

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demotest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappering/UserMapper.xml
  type-aliases-package: com.example.vo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
